/* GENERATED by scripts/build-credits.mjs — do not edit by hand.
   Attribution for everything in the app that carries a licence.
   CC-BY models must stay credited: see the info page on the main menu. */
window.CREDITS_DATA = {
 "models": [
  {
   "slot": "houses/mud-house.glb",
   "name": "Thatched Hut",
   "author": "stealth86",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-bbd820f6e49041b490eb08ac97abfda8"
  },
  {
   "slot": "houses/bungalow.glb",
   "name": "Fantasy Low-Poly Cabin",
   "author": "simonaskLDE",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-9ea62ef7342647c19978a0b053ac1ac0"
  },
  {
   "slot": "houses/tent.glb",
   "name": "Camping Tent",
   "author": "Adeel Qadir",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-21cc274c86104fc997e0f172938d4205"
  },
  {
   "slot": "rooms/kitchen.glb",
   "name": "Low Poly House Interior",
   "author": "Paolo Mercogliano",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-62b1714ef66f4e0d9f42dcd12efb3f52"
  },
  {
   "slot": "rooms/bedroom.glb",
   "name": "Low-Poly PSX Style Wooden Interior Doors Pack",
   "author": "Icevanilla",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-02e442c6d4a24df29624808d058f010a"
  },
  {
   "slot": "rooms/living-room.glb",
   "name": "Low poly living room",
   "author": "Vladek",
   "license": "Free Standard",
   "url": "https://sketchfab.com/3d-models/none-df179eebec234798aa7fbe6c7eaf492a"
  },
  {
   "slot": "plants/tree.glb",
   "name": "Maple tree",
   "author": "atrodler",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-4b27adcf92f644bdabf8ecc6c5bef399"
  },
  {
   "slot": "plants/flower.glb",
   "name": "(FREE) Low Poly Game Assets",
   "author": "LowPolyBoy",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-bbbfbeccfc9047b8b3f15b1c90061cdf"
  },
  {
   "slot": "houses/modern-house.glb",
   "name": "Low poly cartoon Home",
   "author": "Omkar_suryavanshi",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-a90011bff3f349ed91c4b29d9af0293d"
  },
  {
   "slot": "rooms/bathroom.glb",
   "name": "FREE Low Poly Rubber Duck | Basic Materials",
   "author": "wErT",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-6e52dbadef36426fb7fd8adaa00d2b66"
  },
  {
   "slot": "body/human.glb",
   "name": "Set of cartoon characters Low-poly",
   "author": "Pavlov DR",
   "license": "CC Attribution",
   "url": "https://sketchfab.com/3d-models/none-2c65f1af604847429f1ca44157ca4bfa"
  }
 ],
 "photos": [
  {
   "author": "Erwin Bosman",
   "count": 5
  },
  {
   "author": "Adrian Roberts",
   "count": 2
  },
  {
   "author": "Ayşegül  Aytören",
   "count": 2
  },
  {
   "author": "Krepesh Chandra Sarker",
   "count": 2
  },
  {
   "author": "mitbg000",
   "count": 2
  },
  {
   "author": "Yan Krukau",
   "count": 2
  },
  {
   "author": "Yiğit  KARAALİOĞLU",
   "count": 2
  },
  {
   "author": "_ Whittington",
   "count": 1
  },
  {
   "author": "Abdulrhman Alkady",
   "count": 1
  },
  {
   "author": "ALENA MARUK",
   "count": 1
  },
  {
   "author": "Alex Green",
   "count": 1
  },
  {
   "author": "Alexas Fotos",
   "count": 1
  },
  {
   "author": "Alexey Demidov",
   "count": 1
  },
  {
   "author": "Alina Autumn",
   "count": 1
  },
  {
   "author": "Andy Bergstrom",
   "count": 1
  },
  {
   "author": "Bakytzhan  Baurzhanov",
   "count": 1
  },
  {
   "author": "Beat Bieri",
   "count": 1
  },
  {
   "author": "Beyza Şükran DEMİRBAŞ",
   "count": 1
  },
  {
   "author": "Brett Sayles",
   "count": 1
  },
  {
   "author": "Channabo Yos",
   "count": 1
  },
  {
   "author": "chris clark",
   "count": 1
  },
  {
   "author": "Clarence Gaspar",
   "count": 1
  },
  {
   "author": "Curtis Adams",
   "count": 1
  },
  {
   "author": "Daniel  Wells",
   "count": 1
  },
  {
   "author": "DI LAI",
   "count": 1
  },
  {
   "author": "Dong Le",
   "count": 1
  },
  {
   "author": "Dr. Kamal K Varshney",
   "count": 1
  },
  {
   "author": "Dustin Konrad",
   "count": 1
  },
  {
   "author": "Eduardo HernandezSoto",
   "count": 1
  },
  {
   "author": "Edwin Lopez",
   "count": 1
  },
  {
   "author": "Ellie Burgin",
   "count": 1
  },
  {
   "author": "Fabiano Junior",
   "count": 1
  },
  {
   "author": "Feri Feri",
   "count": 1
  },
  {
   "author": "Giulia Botan",
   "count": 1
  },
  {
   "author": "Gizem Gökce",
   "count": 1
  },
  {
   "author": "Guillermo Berlin",
   "count": 1
  },
  {
   "author": "Hakan Sapci",
   "count": 1
  },
  {
   "author": "Ivan Xolod",
   "count": 1
  },
  {
   "author": "Jacek Jan Skorupski",
   "count": 1
  },
  {
   "author": "Jakob  Vargis",
   "count": 1
  },
  {
   "author": "Jared VanderMeer",
   "count": 1
  },
  {
   "author": "Jason Renfrow Photography",
   "count": 1
  },
  {
   "author": "kabita Darlami",
   "count": 1
  },
  {
   "author": "Krishna Soni",
   "count": 1
  },
  {
   "author": "Kristina Evstifeeva",
   "count": 1
  },
  {
   "author": "Layth Mushreq",
   "count": 1
  },
  {
   "author": "Leon Huang",
   "count": 1
  },
  {
   "author": "Lorna Pauli",
   "count": 1
  },
  {
   "author": "Market In SAS",
   "count": 1
  },
  {
   "author": "Markus Winkler",
   "count": 1
  },
  {
   "author": "Max Vakhtbovych",
   "count": 1
  },
  {
   "author": "Mazzu71 - Marco Mazzucotelli",
   "count": 1
  },
  {
   "author": "Natalia Yurashku",
   "count": 1
  },
  {
   "author": "Nguyen Ngoc Tien",
   "count": 1
  },
  {
   "author": "Odd Rune Falch",
   "count": 1
  },
  {
   "author": "Pankaj Mishra",
   "count": 1
  },
  {
   "author": "Petr Ganaj",
   "count": 1
  },
  {
   "author": "Q. Hưng Phạm",
   "count": 1
  },
  {
   "author": "Rahul Sapra",
   "count": 1
  },
  {
   "author": "Ran Lu",
   "count": 1
  },
  {
   "author": "Rohan Dalal",
   "count": 1
  },
  {
   "author": "Rovshan Nazirli",
   "count": 1
  },
  {
   "author": "Ruben Reijgwart",
   "count": 1
  },
  {
   "author": "Saddam Umar  Husain",
   "count": 1
  },
  {
   "author": "Sanalbalan K",
   "count": 1
  },
  {
   "author": "Sergej  *****",
   "count": 1
  },
  {
   "author": "Singlár Zsuzsa",
   "count": 1
  },
  {
   "author": "SnipeShot",
   "count": 1
  },
  {
   "author": "Son Hoa Nguyen",
   "count": 1
  },
  {
   "author": "Steven May",
   "count": 1
  },
  {
   "author": "Tarun Baisoya",
   "count": 1
  },
  {
   "author": "Ulises León",
   "count": 1
  },
  {
   "author": "Vadim Malitskii",
   "count": 1
  },
  {
   "author": "Valentin Foursac",
   "count": 1
  },
  {
   "author": "Valentin Ivantsov",
   "count": 1
  },
  {
   "author": "Wladimir Miranda",
   "count": 1
  },
  {
   "author": "Zetong Li",
   "count": 1
  },
  {
   "author": "Наталья Масик",
   "count": 1
  }
 ]
};
