/**
 * build-credits.mjs — collect every attribution into one file the app can show
 * ══════════════════════════════════════════════════════════════════════════
 *
 *     npm run credits
 *
 * WHY THIS EXISTS
 *   The 3D models are CC-BY. That licence *requires* visible credit wherever
 *   the work is shown, and this app is installed in a centre rather than left
 *   on a laptop — so the obligation is real and ongoing, not a formality.
 *   Pexels does not require attribution, but their API guidelines ask for the
 *   photographer, and it costs nothing to honour that in the same place.
 *
 *   Both fetch scripts write their own credits.json. This merges them into
 *   js/credits-data.js so the info page has one thing to read.
 *
 * WHY A .js AND NOT THE .json FILES
 *   Same reason as js/voice-manifest.js and js/model-manifest.js: the app runs
 *   from file:// inside Electron, where fetching a local JSON file is an
 *   avoidable way to fail. A <script> that assigns a global always works.
 *
 * RE-RUN after either fetch script. `npm run models` and `npm run photos` both
 * call it, so normally you never run it by hand.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = decodeURIComponent(new URL('..', import.meta.url).pathname)
  .replace(/^\/([A-Za-z]:)/, '$1');

const MODELS = join(ROOT, 'assets', 'new', 'models', 'credits.json');
const PHOTOS = join(ROOT, 'assets', 'new', 'images', 'credits.json');
const OUT = join(ROOT, 'js', 'credits-data.js');

function read(path) {
  if (!existsSync(path)) return {};
  try { return JSON.parse(readFileSync(path, 'utf8')); } catch { return {}; }
}

const models = Object.entries(read(MODELS)).map(([slot, m]) => ({
  slot,
  name: m.name || slot,
  author: m.author || 'unknown',
  license: m.license || 'unknown',
  url: m.modelUrl || ''
}));

/* Photographers repeat across the 88 photos — one line per person, with how
   many pictures of theirs are in the app, is far more readable on a wall than
   88 near-identical rows. */
const byPhotographer = {};
for (const info of Object.values(read(PHOTOS))) {
  const who = (info && info.photographer) || 'unknown';
  byPhotographer[who] = (byPhotographer[who] || 0) + 1;
}
const photos = Object.entries(byPhotographer)
  .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
  .map(([author, count]) => ({ author, count }));

const out =
`/* GENERATED by scripts/build-credits.mjs — do not edit by hand.
   Attribution for everything in the app that carries a licence.
   CC-BY models must stay credited: see the info page on the main menu. */
window.CREDITS_DATA = ${JSON.stringify({ models, photos }, null, 1)};
`;

writeFileSync(OUT, out, 'utf8');
console.log(`credits -> js/credits-data.js  (${models.length} model(s), ` +
            `${photos.length} photographer(s))`);
